// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxj3Arn07dFIXjTlFKO6x0_WheXHm8bH8',
    appId: '1:805618462359:web:c8a628703548bbec0ec3d2',
    messagingSenderId: '805618462359',
    projectId: 'crudfinal-489e8',
    authDomain: 'crudfinal-489e8.firebaseapp.com',
    storageBucket: 'crudfinal-489e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAseccMdLlfDrN21Tv4zoG5AtNN8lim3LI',
    appId: '1:805618462359:android:d44cd685ed692f530ec3d2',
    messagingSenderId: '805618462359',
    projectId: 'crudfinal-489e8',
    storageBucket: 'crudfinal-489e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zltF-A7jDYu5WOjFpVYQ5SV-YlRX3Xo',
    appId: '1:805618462359:ios:8b19855bfc93a0bb0ec3d2',
    messagingSenderId: '805618462359',
    projectId: 'crudfinal-489e8',
    storageBucket: 'crudfinal-489e8.appspot.com',
    iosBundleId: 'com.example.flutterCrudfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zltF-A7jDYu5WOjFpVYQ5SV-YlRX3Xo',
    appId: '1:805618462359:ios:4ce43f11156abc4b0ec3d2',
    messagingSenderId: '805618462359',
    projectId: 'crudfinal-489e8',
    storageBucket: 'crudfinal-489e8.appspot.com',
    iosBundleId: 'com.example.flutterCrudfinal.RunnerTests',
  );
}
